from __future__ import annotations

import runpy
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "build_workbench_assets.py"
BUILDER = runpy.run_path(str(SCRIPT))

PRODUCTION_MODULES = [
    "10_state_persistence.js",
    "15_product_shell.js",
    "20_review_core.js",
    "24_cfar_mask_annotation.js",
    "25_review_controls.js",
    "30_architecture_lab.js",
    "40_experiment_lab.js",
    "50_pipeline_builder.js",
    "60_metrics_report.js",
    "70_dataset_qc.js",
    "80_review_subpages.js",
    "90_boot.js",
]


class WorkbenchAssetBuildTests(unittest.TestCase):
    def test_production_manifest_defines_exact_bundle_order(self):
        source_dir = ROOT / "neurobench" / "workbench" / "assets" / "src"
        manifest = source_dir / "bundle_sources.txt"
        entries = [
            line.strip()
            for line in manifest.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]

        files = BUILDER["source_files"](source_dir)

        self.assertEqual(entries, PRODUCTION_MODULES)
        self.assertEqual([path.name for path in files], PRODUCTION_MODULES)

    def test_production_manifest_rejects_missing_listed_source(self):
        with tempfile.TemporaryDirectory() as tmp:
            source_dir = Path(tmp) / "src"
            source_dir.mkdir()
            manifest = source_dir / "bundle_sources.txt"
            manifest.write_text("10_present.js\n20_missing.js\n", encoding="utf-8")
            (source_dir / "10_present.js").write_text("window.present = true;\n", encoding="utf-8")

            with self.assertRaisesRegex(ValueError, r"missing listed module\(s\): 20_missing\.js"):
                BUILDER["manifest_source_files"](source_dir, manifest)

    def test_production_manifest_rejects_unexpected_source(self):
        with tempfile.TemporaryDirectory() as tmp:
            source_dir = Path(tmp) / "src"
            source_dir.mkdir()
            manifest = source_dir / "bundle_sources.txt"
            manifest.write_text("10_present.js\n", encoding="utf-8")
            (source_dir / "10_present.js").write_text("window.present = true;\n", encoding="utf-8")
            (source_dir / "20_unlisted.js").write_text("window.unlisted = true;\n", encoding="utf-8")

            with self.assertRaisesRegex(ValueError, r"unexpected module\(s\).*20_unlisted\.js"):
                BUILDER["manifest_source_files"](source_dir, manifest)

    def test_custom_source_dir_uses_sorted_fallback_without_manifest(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source_dir = root / "src"
            out = root / "workbench.js"
            source_dir.mkdir()
            (source_dir / "20_second.js").write_text("window.second = true;\n", encoding="utf-8")
            (source_dir / "10_first.js").write_text("window.first = true;\n", encoding="utf-8")

            result = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out)],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )

            bundle = out.read_text(encoding="utf-8")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertFalse((source_dir / "bundle_sources.txt").exists())
        self.assertIn("Generated by tools/build_workbench_assets.py", bundle)
        self.assertLess(bundle.index("10_first.js"), bundle.index("20_second.js"))
        self.assertLess(bundle.index("window.first"), bundle.index("window.second"))

    def test_asset_builder_check_detects_stale_bundle(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source_dir = root / "src"
            out = root / "workbench.js"
            source_dir.mkdir()
            module = source_dir / "10_module.js"
            module.write_text("window.value = 1;\n", encoding="utf-8")

            build = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out)],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            fresh_check = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out), "--check"],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            module.write_text("window.value = 2;\n", encoding="utf-8")
            stale_check = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out), "--check"],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )

        self.assertEqual(build.returncode, 0, build.stderr)
        self.assertEqual(fresh_check.returncode, 0, fresh_check.stderr)
        self.assertEqual(stale_check.returncode, 1)
        self.assertIn("stale", stale_check.stderr)

    def test_asset_builder_can_initialize_source_from_current_bundle(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source_dir = root / "src"
            current = root / "current_workbench.js"
            out = root / "workbench.js"
            current.write_text("window.currentWorkbench = true;\n", encoding="utf-8")

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--source-dir",
                    str(source_dir),
                    "--out",
                    str(out),
                    "--init-from-current",
                    str(current),
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )

            source = source_dir / "90_workbench.monolith.js"
            bundle = out.read_text(encoding="utf-8")
            source_exists = source.is_file()
            source_text = source.read_text(encoding="utf-8")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(source_exists)
        self.assertIn("window.currentWorkbench = true;", source_text)
        self.assertIn("90_workbench.monolith.js", bundle)
        self.assertIn("window.currentWorkbench = true;", bundle)

    def test_init_from_current_rejects_production_source_before_writing(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            protected_source_dir = root / "production-src"
            current = root / "current_workbench.js"
            current.write_text("window.currentWorkbench = true;\n", encoding="utf-8")
            initialize = BUILDER["initialize_from_current_bundle"]

            with mock.patch.dict(initialize.__globals__, {"DEFAULT_SOURCE_DIR": protected_source_dir}):
                with self.assertRaisesRegex(ValueError, r"cannot target the production source directory"):
                    initialize(protected_source_dir, current)

            self.assertFalse(protected_source_dir.exists())
            self.assertFalse((protected_source_dir / "90_workbench.monolith.js").exists())


class WorkbenchCandidateOverlayViewTests(unittest.TestCase):
    def test_review_template_has_raw_and_overlay_panes(self):
        html = (ROOT / "neurobench" / "workbench" / "assets" / "workbench.html").read_text(encoding="utf-8")
        self.assertIn('id="reviewSideBySideBtn"', html)
        self.assertIn('id="reviewRawFrameImg"', html)
        self.assertIn('Candidate / event outline', html)

    def test_candidate_only_runs_use_single_review_canvas_and_live_data_compare(self):
        source_root = ROOT / "neurobench" / "workbench" / "assets" / "src"
        state = (source_root / "10_state_persistence.js").read_text(encoding="utf-8")
        qc = (source_root / "70_dataset_qc.js").read_text(encoding="utf-8")
        metrics = (source_root / "60_metrics_report.js").read_text(encoding="utf-8")
        self.assertIn("candidateOverlayOnlyRun(runId) ? 'raw_roi'", state)
        self.assertIn("reviewSideBySide: false", state)
        self.assertIn("annotations.settings.reviewSideBySide = false", state)
        self.assertIn("runHasCandidateRois(run) && !runHasIntermediates(run)", qc)
        self.assertIn("no duplicate intermediate frame stack is required", metrics)


if __name__ == "__main__":
    unittest.main()
