from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "build_workbench_assets.py"


class WorkbenchAssetBuildTests(unittest.TestCase):
    def test_asset_builder_orders_modules(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source_dir = root / "src"
            out = root / "workbench.js"
            source_dir.mkdir()
            (source_dir / "20_second.js").write_text("window.second = true;\n", encoding="utf-8")
            (source_dir / "10_first.js").write_text("window.first = true;\n", encoding="utf-8")

            result = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out)],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )

            bundle = out.read_text(encoding="utf-8")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("Generated by tools/build_workbench_assets.py", bundle)
        self.assertLess(bundle.index("10_first.js"), bundle.index("20_second.js"))
        self.assertLess(bundle.index("window.first"), bundle.index("window.second"))

    def test_asset_builder_check_detects_stale_bundle(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source_dir = root / "src"
            out = root / "workbench.js"
            source_dir.mkdir()
            module = source_dir / "10_module.js"
            module.write_text("window.value = 1;\n", encoding="utf-8")

            build = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out)],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            fresh_check = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out), "--check"],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            module.write_text("window.value = 2;\n", encoding="utf-8")
            stale_check = subprocess.run(
                [sys.executable, str(SCRIPT), "--source-dir", str(source_dir), "--out", str(out), "--check"],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )

        self.assertEqual(build.returncode, 0, build.stderr)
        self.assertEqual(fresh_check.returncode, 0, fresh_check.stderr)
        self.assertEqual(stale_check.returncode, 1)
        self.assertIn("stale", stale_check.stderr)

    def test_asset_builder_can_initialize_source_from_current_bundle(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source_dir = root / "src"
            current = root / "current_workbench.js"
            out = root / "workbench.js"
            current.write_text("window.currentWorkbench = true;\n", encoding="utf-8")

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--source-dir",
                    str(source_dir),
                    "--out",
                    str(out),
                    "--init-from-current",
                    str(current),
                ],
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )

            source = source_dir / "90_workbench.monolith.js"
            bundle = out.read_text(encoding="utf-8")
            source_exists = source.is_file()
            source_text = source.read_text(encoding="utf-8")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(source_exists)
        self.assertIn("window.currentWorkbench = true;", source_text)
        self.assertIn("90_workbench.monolith.js", bundle)
        self.assertIn("window.currentWorkbench = true;", bundle)


if __name__ == "__main__":
    unittest.main()
