#!/usr/bin/env python3
"""Import the validated full-trace feature panel into the manuscript package."""
from __future__ import annotations

import csv
import hashlib
import json
import shutil
from pathlib import Path

from neurobench.portable_paths import data_root, media_root, portable_path, portableize_paths


PAPER = Path(__file__).resolve().parents[1]
REPO = PAPER.parents[1]
RUN = REPO / "Outputs/NeuronIdentifiability/spon_ca_burst_full_trace_feature_panel_v2"
FINAL = PAPER / "figures/final"
GENERATED = PAPER / "generated_analysis/full_trace_feature_panel_v2"
MACROS = PAPER / "macros/full_trace_feature_panel.tex"
TABLE = PAPER / "tables/full_trace_feature_panel_summary.tex"
PROVENANCE = FINAL / "fig08_full_trace_feature_panel.json"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(path.suffix + ".partial")
    partial.write_text(text, encoding="utf-8")
    partial.replace(path)


def atomic_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_suffix(destination.suffix + ".partial")
    shutil.copy2(source, partial)
    partial.replace(destination)


def atomic_portable_json_copy(source: Path, destination: Path) -> None:
    payload = portableize_paths(
        json.loads(source.read_text(encoding="utf-8")),
        repository=REPO,
        data=data_root(REPO),
        media=media_root(REPO),
    )
    atomic_text(destination, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def tex_escape(value: str) -> str:
    return value.replace("&", r"\&").replace("_", r"\_").replace("%", r"\%")


def main() -> int:
    status = json.loads((RUN / "status.json").read_text(encoding="utf-8"))
    validation = json.loads((RUN / "validation.json").read_text(encoding="utf-8"))
    if status != {"schema_version": 1, "status": "complete_exploratory", "validation": "passed"}:
        raise RuntimeError(f"unexpected run status: {status}")
    if validation.get("status") != "passed" or not all(validation.get("checks", {}).values()):
        raise RuntimeError(f"run validation did not pass: {validation}")

    index = json.loads((RUN / "artifact_index.json").read_text(encoding="utf-8"))
    for artifact in index["artifacts"]:
        source = RUN / artifact["path"]
        if not source.is_file() or source.stat().st_size != artifact["bytes"] or sha256(source) != artifact["sha256"]:
            raise RuntimeError(f"artifact index mismatch: {artifact['path']}")

    summary = json.loads((RUN / "summary.json").read_text(encoding="utf-8"))
    with (RUN / "tables/feature_summary.tsv").open(encoding="utf-8") as handle:
        feature_rows = list(csv.DictReader(handle, delimiter="\t"))
    with (RUN / "tables/occurrence_feature_metrics.tsv").open(encoding="utf-8") as handle:
        occurrence_rows = list(csv.DictReader(handle, delimiter="\t"))
    by_feature = {row["feature_id"]: row for row in feature_rows}

    figure_source = RUN / "figures/full_trace_feature_panel.png"
    figure_target = FINAL / "fig08_full_trace_feature_panel.png"
    atomic_copy(figure_source, figure_target)
    for relative in (
        "summary.json",
        "validation.json",
        "artifact_index.json",
        "tables/feature_summary.tsv",
        "tables/burst_feature_summary.tsv",
        "tables/burst_pair_repeatability.tsv",
    ):
        destination = GENERATED / Path(relative).name
        if Path(relative).suffix == ".json" and Path(relative).name != "artifact_index.json":
            atomic_portable_json_copy(RUN / relative, destination)
        else:
            atomic_copy(RUN / relative, destination)

    def value(feature: str, field: str) -> float:
        return float(by_feature[feature][field])

    ceiling = {
        feature: sum(
            row["feature_id"] == feature and float(row["event_localization_percentile"]) == 1.0
            for row in occurrence_rows
        )
        for feature in ("carrier_signed", "coherence_w15", "propagation_lag2_w15")
    }
    macro_lines = [
        "% Generated by scripts/import_fig08_full_trace_feature_panel.py; do not edit.",
        rf"\newcommand{{\FullTraceOccurrences}}{{{summary['population']['occurrences']}}}",
        rf"\newcommand{{\FullTraceSites}}{{{summary['population']['sites']}}}",
        rf"\newcommand{{\FullTraceCarrierPercentile}}{{{value('carrier_signed', 'mean_event_localization_percentile'):.3f}}}",
        rf"\newcommand{{\FullTraceCarrierCILow}}{{{value('carrier_signed', 'ci95_low'):.3f}}}",
        rf"\newcommand{{\FullTraceCarrierCIHigh}}{{{value('carrier_signed', 'ci95_high'):.3f}}}",
        rf"\newcommand{{\FullTraceCoherencePercentile}}{{{value('coherence_w15', 'mean_event_localization_percentile'):.3f}}}",
        rf"\newcommand{{\FullTraceLagPercentile}}{{{value('propagation_lag2_w15', 'mean_event_localization_percentile'):.3f}}}",
        rf"\newcommand{{\FullTraceLagDelta}}{{{value('propagation_lag2_w15', 'paired_delta_vs_carrier'):+.3f}}}",
        rf"\newcommand{{\FullTraceLagDeltaLow}}{{{value('propagation_lag2_w15', 'paired_delta_ci95_low'):.3f}}}",
        rf"\newcommand{{\FullTraceLagDeltaHigh}}{{{value('propagation_lag2_w15', 'paired_delta_ci95_high'):.3f}}}",
        rf"\newcommand{{\FullTraceRawPercentile}}{{{value('raw_center', 'mean_event_localization_percentile'):.3f}}}",
        rf"\newcommand{{\FullTraceConsensusPercentile}}{{{value('representation_consensus', 'mean_event_localization_percentile'):.3f}}}",
        rf"\newcommand{{\FullTraceConsensusRepeatability}}{{{value('representation_consensus', 'median_burst_pair_spearman'):.3f}}}",
        rf"\newcommand{{\FullTracePersistencePercentile}}{{{value('multiscale_persistence', 'mean_event_localization_percentile'):.3f}}}",
        rf"\newcommand{{\FullTracePersistenceRepeatability}}{{{value('multiscale_persistence', 'median_burst_pair_spearman'):.3f}}}",
        rf"\newcommand{{\FullTraceVSTPercentile}}{{{value('vst_center_annulus', 'mean_event_localization_percentile'):.3f}}}",
        rf"\newcommand{{\FullTraceCarrierCeilingCount}}{{{ceiling['carrier_signed']}}}",
        rf"\newcommand{{\FullTraceCoherenceCeilingCount}}{{{ceiling['coherence_w15']}}}",
        rf"\newcommand{{\FullTraceLagCeilingCount}}{{{ceiling['propagation_lag2_w15']}}}",
        "",
    ]
    atomic_text(MACROS, "\n".join(macro_lines))

    table_lines = [
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\scriptsize",
        r"\begin{tabularx}{\linewidth}{X r r r}",
        r"\toprule",
        r"Feature & Mean percentile [95\% CI] & $\Delta$ vs carrier & Median $\rho$ \\",
        r"\midrule",
    ]
    for row in feature_rows:
        rho = row["median_burst_pair_spearman"]
        rho_text = "--" if rho == "" else f"{float(rho):.3f}"
        table_lines.append(
            f"{tex_escape(row['feature_label'])} & "
            f"{float(row['mean_event_localization_percentile']):.3f} "
            f"[{float(row['ci95_low']):.3f}, {float(row['ci95_high']):.3f}] & "
            f"{float(row['paired_delta_vs_carrier']):+.3f} & {rho_text} \\\\"
        )
    table_lines += [
        r"\bottomrule",
        r"\end{tabularx}",
        r"\caption{Exploratory full-trace feature panel at confirmed ROI centers. Percentiles compare each confirmed event maximum with all same-duration quiet-window maxima at the same immutable site; intervals use a 5,000-draw site bootstrap. The final column is the median available burst-pair Spearman correlation of site ranks; dashes denote ceiling-induced undefined correlations.}",
        r"\label{tab:full-trace-feature-panel}",
        r"\end{table}",
        "",
    ]
    atomic_text(TABLE, "\n".join(table_lines))

    provenance = {
        "status": "imported_from_validated_exploratory_run",
        "source_run": portable_path(RUN, repository=REPO),
        "source_status": status,
        "source_artifact_index_sha256": sha256(RUN / "artifact_index.json"),
        "source_summary_sha256": sha256(RUN / "summary.json"),
        "source_figure_sha256": sha256(figure_source),
        "imported_figure_sha256": sha256(figure_target),
        "population": summary["population"],
        "interpretation_limits": summary["interpretation_limits"],
    }
    atomic_text(PROVENANCE, json.dumps(provenance, indent=2, sort_keys=True) + "\n")
    print(json.dumps(provenance, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
