#!/usr/bin/env python3
"""Import the validated automated feature suite into the manuscript package."""
from __future__ import annotations

import csv
import hashlib
import json
import shutil
from pathlib import Path

from neurobench.portable_paths import portable_path

PAPER = Path(__file__).resolve().parents[1]
REPO = PAPER.parents[1]
RUN = REPO / "Outputs/NeuronIdentifiability/spon_ca_burst_automated_feature_validation_v1"
FINAL = PAPER / "figures/final"
GENERATED = PAPER / "generated_analysis/automated_feature_validation_v1"
MACROS = PAPER / "macros/automated_feature_validation.tex"
TABLE = PAPER / "tables/automated_feature_validation_summary.tex"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(path.suffix + ".partial")
    partial.write_text(text, encoding="utf-8")
    partial.replace(path)


def atomic_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_suffix(destination.suffix + ".partial")
    shutil.copy2(source, partial)
    partial.replace(destination)


def read_table(name: str) -> list[dict[str, str]]:
    with (RUN / "tables" / name).open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def main() -> int:
    status = json.loads((RUN / "status.json").read_text())
    validation = json.loads((RUN / "validation.json").read_text())
    if status != {"status": "complete", "validation": "passed"}:
        raise RuntimeError(f"unexpected run status: {status}")
    if validation.get("status") != "passed" or not all(validation.get("checks", {}).values()):
        raise RuntimeError(f"run validation did not pass: {validation}")
    index = json.loads((RUN / "artifact_index.json").read_text())
    for artifact in index["artifacts"]:
        source = RUN / artifact["path"]
        if not source.is_file() or source.stat().st_size != artifact["bytes"] or sha256(source) != artifact["sha256"]:
            raise RuntimeError(f"artifact index mismatch: {artifact['path']}")

    for source_name, target_name in (
        ("automated_validation_overview.png", "fig09_automated_feature_validation.png"),
        ("robustness_falsification.png", "fig10_robustness_falsification.png"),
    ):
        atomic_copy(RUN / "figures" / source_name, FINAL / target_name)
    for relative in (
        "summary.json", "validation.json", "artifact_index.json",
        "tables/temporal_retrieval_summary.tsv", "tables/spatial_displacement_summary.tsv",
        "tables/recovery_model_summary.tsv", "tables/recovery_model_ablation.tsv",
        "tables/reliability_summary.tsv", "tables/null_calibration.tsv",
    ):
        atomic_copy(RUN / relative, GENERATED / Path(relative).name)

    temporal = {r["feature_id"]: r for r in read_table("temporal_retrieval_summary.tsv")}
    spatial = {r["feature_id"]: r for r in read_table("spatial_displacement_summary.tsv")}
    recovery = read_table("recovery_model_summary.tsv")
    primary = {r["model"]: r for r in recovery if r["population"] == "106_original_geometries"}
    reliability = {r["feature_id"]: r for r in read_table("reliability_summary.tsv")}
    nulls = {r["feature_id"]: r for r in read_table("null_calibration.tsv")}
    macros = [
        "% Generated by scripts/import_fig09_automated_feature_validation.py; do not edit.",
        rf"\newcommand{{\AutoRawAUC}}{{{float(temporal['raw_center']['mean_frame_auc']):.3f}}}",
        rf"\newcommand{{\AutoRawAUCLow}}{{{float(temporal['raw_center']['frame_auc_ci95_low']):.3f}}}",
        rf"\newcommand{{\AutoRawAUCHigh}}{{{float(temporal['raw_center']['frame_auc_ci95_high']):.3f}}}",
        rf"\newcommand{{\AutoCarrierAUC}}{{{float(temporal['carrier_signed']['mean_frame_auc']):.3f}}}",
        rf"\newcommand{{\AutoCoherenceAUC}}{{{float(temporal['coherence_w15']['mean_frame_auc']):.3f}}}",
        rf"\newcommand{{\AutoLagAUC}}{{{float(temporal['propagation_lag2_w15']['mean_frame_auc']):.3f}}}",
        rf"\newcommand{{\AutoMatchedAUC}}{{{float(temporal['matched_filter_ls']['mean_frame_auc']):.3f}}}",
        rf"\newcommand{{\AutoPersistenceSpatialDelta}}{{{float(spatial['multiscale_persistence']['mean_target_minus_displaced_auc']):.3f}}}",
        rf"\newcommand{{\AutoRecoveryCount}}{{{primary['carrier_only']['recovered']}}}",
        rf"\newcommand{{\AutoRecoveryMisses}}{{{primary['carrier_only']['missed']}}}",
        rf"\newcommand{{\AutoCarrierLogLoss}}{{{float(primary['carrier_only']['log_loss']):.3f}}}",
        rf"\newcommand{{\AutoExtendedLogLoss}}{{{float(primary['extended_role_specific']['log_loss']):.3f}}}",
        rf"\newcommand{{\AutoRecoveryDelta}}{{{float(primary['extended_role_specific']['log_loss_improvement_vs_carrier']):.3f}}}",
        rf"\newcommand{{\AutoRecoveryDeltaLow}}{{{float(primary['extended_role_specific']['site_bootstrap_improvement_ci95_low']):.3f}}}",
        rf"\newcommand{{\AutoRecoveryDeltaHigh}}{{{float(primary['extended_role_specific']['site_bootstrap_improvement_ci95_high']):.3f}}}",
        rf"\newcommand{{\AutoCarrierReliability}}{{{float(reliability['carrier_signed']['conditional_site_variance_fraction_nonparametric']):.3f}}}",
        rf"\newcommand{{\AutoAnnulusReliability}}{{{float(reliability['raw_center_annulus']['conditional_site_variance_fraction_nonparametric']):.3f}}}",
        rf"\newcommand{{\AutoNullP}}{{{float(nulls['raw_center']['empirical_upper_tail_p']):.4f}}}",
        "",
    ]
    atomic_text(MACROS, "\n".join(macros))

    selected = ("raw_center", "carrier_signed", "coherence_w15", "propagation_lag2_w15", "matched_filter_ls", "representation_consensus", "multiscale_persistence", "raw_center_annulus")
    row_end = r"\\"
    lines = [r"\begin{table}[!htbp]", r"\centering", r"\scriptsize", r"\begin{tabularx}{\linewidth}{X r r r}", r"\toprule", "Feature & Frame AUC [95\\% CI] & Spatial $\\Delta$ AUC & Site fraction " + row_end, r"\midrule"]
    for feature in selected:
        tr = temporal[feature]
        spatial_text = f"{float(spatial[feature]['mean_target_minus_displaced_auc']):.3f}" if feature in spatial else "--"
        label = tr["feature_label"].replace("&", r"\&")
        lines.append(f"{label} & {float(tr['mean_frame_auc']):.3f} [{float(tr['frame_auc_ci95_low']):.3f}, {float(tr['frame_auc_ci95_high']):.3f}] & {spatial_text} & {float(reliability[feature]['conditional_site_variance_fraction_nonparametric']):.3f} " + row_end)
    lines += [r"\bottomrule", r"\end{tabularx}", r"\caption{Automated full-trace validation. Frame AUC separates annotated event frames from guarded quiet-reference frames. Spatial differences compare the true center with same-field baseline-matched displaced tissue. Site fraction is a nonparametric variance fraction, not REML ICC. Quiet and displaced references have unknown biological labels.}", r"\label{tab:automated-feature-validation}", r"\end{table}", ""]
    atomic_text(TABLE, "\n".join(lines))

    provenance = {
        "status": "imported_from_validated_automated_suite",
        "source_run": portable_path(RUN, repository=REPO),
        "source_artifact_index_sha256": sha256(RUN / "artifact_index.json"),
        "source_summary_sha256": sha256(RUN / "summary.json"),
        "population": json.loads((RUN / "summary.json").read_text())["population"],
    }
    atomic_text(FINAL / "fig09_automated_feature_validation.json", json.dumps(provenance, indent=2, sort_keys=True) + "\n")
    print(json.dumps(provenance, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
