#!/usr/bin/env python3
"""Import the validated canonical-v7 deep-dive suite."""
from __future__ import annotations

import csv
import hashlib
import json
import shutil
from pathlib import Path

from neurobench.portable_paths import data_root, media_root, portable_path, portableize_paths

PAPER = Path(__file__).resolve().parents[1]
REPO = PAPER.parents[1]
RUN = REPO / "Outputs/NeuronIdentifiability/spon_ca_burst_feature_deep_dives_v2"
FINAL = PAPER / "figures/final"
GENERATED = PAPER / "generated_analysis/feature_deep_dives_v1"
MACROS = PAPER / "macros/feature_deep_dives.tex"


def sha256(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def atomic_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_suffix(destination.suffix + ".partial")
    shutil.copy2(source, partial); partial.replace(destination)


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(path.suffix + ".partial")
    partial.write_text(text, encoding="utf-8"); partial.replace(path)


def atomic_portable_json_copy(source: Path, destination: Path) -> None:
    payload = portableize_paths(
        json.loads(source.read_text(encoding="utf-8")),
        repository=REPO,
        data=data_root(REPO),
        media=media_root(REPO),
    )
    atomic_text(destination, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def table(name: str) -> list[dict[str, str]]:
    with (RUN / "tables" / name).open(encoding="utf-8") as stream:
        return list(csv.DictReader(stream, delimiter="\t"))


def main() -> int:
    status = json.loads((RUN / "status.json").read_text())
    validation = json.loads((RUN / "validation.json").read_text())
    if status.get("status") != "complete" or validation.get("status") != "passed" or not all(validation["checks"].values()):
        raise RuntimeError("deep-dive run is not validated")
    for artifact in json.loads((RUN / "artifact_index.json").read_text())["artifacts"]:
        source = RUN / artifact["path"]
        if source.stat().st_size != artifact["bytes"] or sha256(source) != artifact["sha256"]:
            raise RuntimeError(f"artifact mismatch: {artifact['path']}")
    for source, destination in (("deep_dive_overview.png", "fig11_feature_deep_dives.png"), ("spatial_decay_crowding.png", "fig12_spatial_decay_crowding.png")):
        atomic_copy(RUN / "figures" / source, FINAL / destination)
    for relative in ("summary.json", "validation.json", "artifact_index.json", "tables/failure_taxonomy_summary.tsv", "tables/proposal_ranking_decomposition.tsv", "tables/kinetic_bank_lobo_selection.tsv", "tables/recovery_complementarity.tsv", "tables/coherence_lag_mechanism_audit.tsv"):
        destination = GENERATED / Path(relative).name
        if Path(relative).suffix == ".json" and Path(relative).name != "artifact_index.json":
            atomic_portable_json_copy(RUN / relative, destination)
        else:
            atomic_copy(RUN / relative, destination)
    summary = json.loads((RUN / "summary.json").read_text()); headline = summary["headline"]
    failures = {row["failure_taxonomy"]: row for row in table("failure_taxonomy_summary.tsv")}
    p20 = {row["feature_id"]: row for row in table("proposal_ranking_decomposition.tsv") if row["budget"] == "20"}
    macros = [
        "% Generated by scripts/import_fig11_feature_deep_dives.py; do not edit.",
        rf"\newcommand{{\DeepRecoveredAll}}{{{failures['recovered_all_lanes']['occurrences']}}}",
        rf"\newcommand{{\DeepRecoveredPartial}}{{{failures['partial_lane_recovery']['occurrences']}}}",
        rf"\newcommand{{\DeepAllMisses}}{{{headline['all_lane_misses']}}}",
        rf"\newcommand{{\DeepCoherenceNativeTwenty}}{{{float(p20['coherence_w15']['native_delta_vs_carrier']):.3f}}}",
        rf"\newcommand{{\DeepCoherenceRankingTwenty}}{{{float(p20['coherence_w15']['common_proposal_ranking_delta_vs_carrier']):.3f}}}",
        rf"\newcommand{{\DeepLagNativeTwenty}}{{{float(p20['propagation_lag2_w15']['native_delta_vs_carrier']):.3f}}}",
        rf"\newcommand{{\DeepLagRankingTwenty}}{{{float(p20['propagation_lag2_w15']['common_proposal_ranking_delta_vs_carrier']):.3f}}}",
        rf"\newcommand{{\DeepKineticKernel}}{{{headline['best_fixed_kinetic_kernel']['kernel_id'].replace('_', r'\_')}}}",
        rf"\newcommand{{\DeepKineticAUC}}{{{headline['best_fixed_kinetic_kernel']['site_weighted_mean_frame_auc']:.3f}}}",
        rf"\newcommand{{\DeepKineticLOBOAUC}}{{{headline['lobo_kinetic_mean_auc']:.3f}}}",
        rf"\newcommand{{\DeepCarrierLoss}}{{{headline['carrier_repeated_log_loss']:.3f}}}",
        rf"\newcommand{{\DeepCompactLoss}}{{{headline['compact_three_repeated_log_loss']:.3f}}}",
        "",
    ]
    atomic_text(MACROS, "\n".join(macros))
    provenance = {"status":"imported_from_validated_feature_deep_dives","source_run":portable_path(RUN, repository=REPO),"source_artifact_index_sha256":sha256(RUN/"artifact_index.json"),"population":summary["population"]}
    atomic_text(FINAL/"fig11_feature_deep_dives.json",json.dumps(provenance,indent=2,sort_keys=True)+"\n")
    print(json.dumps(provenance, indent=2)); return 0


if __name__ == "__main__": raise SystemExit(main())
