#!/usr/bin/env python3
"""Build the packaged dashboard JavaScript bundle from ordered source modules."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_DIR = PROJECT_ROOT / "neurobench" / "workbench" / "assets" / "src"
DEFAULT_OUTPUT = PROJECT_ROOT / "neurobench" / "workbench" / "assets" / "workbench.js"
DEFAULT_MONOLITH_SOURCE = DEFAULT_SOURCE_DIR / "90_workbench.monolith.js"

BANNER = """// Generated by tools/build_workbench_assets.py.
// Edit neurobench/workbench/assets/src/*.js, then rebuild this bundle.
"""


def source_files(source_dir: Path) -> list[Path]:
    """Return JavaScript source modules in deterministic bundle order."""
    return sorted(path for path in source_dir.glob("*.js") if path.is_file())


def render_bundle(source_dir: Path) -> str:
    """Render an ordered JavaScript bundle from a source directory."""
    files = source_files(source_dir)
    if not files:
        raise ValueError(f"No .js source modules found in {source_dir}")

    chunks = [BANNER.rstrip(), ""]
    for path in files:
        text = path.read_text(encoding="utf-8").strip()
        chunks.append(f"// --- {path.relative_to(source_dir)} ---")
        chunks.append(text)
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    """Write content only when it differs from the current file."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def initialize_from_current_bundle(source_dir: Path, current_bundle: Path, *, force: bool = False) -> Path:
    """Copy the existing monolithic bundle into the source tree for migration."""
    if not current_bundle.is_file():
        raise FileNotFoundError(f"Current bundle not found: {current_bundle}")
    target = source_dir / DEFAULT_MONOLITH_SOURCE.name
    if target.exists() and not force:
        raise FileExistsError(f"{target} already exists; pass --force to overwrite it")
    source_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(current_bundle.read_text(encoding="utf-8"), encoding="utf-8")
    return target


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR, help="Directory containing ordered *.js modules.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT, help="Output bundle path.")
    parser.add_argument("--check", action="store_true", help="Fail if the output bundle is stale.")
    parser.add_argument(
        "--init-from-current",
        type=Path,
        metavar="CURRENT_BUNDLE",
        help="Copy an existing workbench.js into src/90_workbench.monolith.js before building.",
    )
    parser.add_argument("--force", action="store_true", help="Allow --init-from-current to overwrite an existing monolith source.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    source_dir = args.source_dir.resolve()
    out = args.out.resolve()

    try:
        if args.init_from_current is not None:
            initialized = initialize_from_current_bundle(source_dir, args.init_from_current.resolve(), force=args.force)
            print(f"Initialized source module: {initialized}")

        bundle = render_bundle(source_dir)
        if args.check:
            current = out.read_text(encoding="utf-8") if out.exists() else ""
            if current != bundle:
                print(f"Workbench asset bundle is stale: {out}", file=sys.stderr)
                return 1
            print(f"Workbench asset bundle is up to date: {out}")
            return 0

        changed = write_if_changed(out, bundle)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    status = "Updated" if changed else "Unchanged"
    print(f"{status} workbench asset bundle: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
